schoool-master/Controllers/HomeTasksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using School.Data;
using School.Models;

namespace School.Controllers
{
    public class HomeTasksController : Controller
    {
        private readonly ApplicationDbContext _context;

        public HomeTasksController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: HomeTasks
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Tasks.Include(h => h.Class);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: HomeTasks/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var homeTask = await _context.Tasks
                .Include(h => h.Class)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (homeTask == null)
            {
                return NotFound();
            }

            return View(homeTask);
        }

        // GET: HomeTasks/Create
        public IActionResult Create(int? id)
        {
            ViewData["ClassId"] = id;
            return View();
        }

        // POST: HomeTasks/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Subject,Content,Deadline,ClassId")] HomeTask homeTask)
        {
            if (ModelState.IsValid)
            {
                _context.Add(homeTask);
                await _context.SaveChangesAsync();
                return RedirectToAction("Details", "SchoolClasses", new { id = homeTask.ClassId });
            }
            ViewData["ClassId"] = new SelectList(_context.Classes, "Id", "Id", homeTask.ClassId);
            return View(homeTask);
        }

        // GET: HomeTasks/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var homeTask = await _context.Tasks.FindAsync(id);
            if (homeTask == null)
            {
                return NotFound();
            }
            ViewData["ClassId"] = new SelectList(_context.Classes, "Id", "Id", homeTask.ClassId);
            return View(homeTask);
        }

        // POST: HomeTasks/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Subject,Content,Deadline,ClassId")] HomeTask homeTask)
        {
            if (id != homeTask.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(homeTask);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!HomeTaskExists(homeTask.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["ClassId"] = new SelectList(_context.Classes, "Id", "Id", homeTask.ClassId);
            return View(homeTask);
        }

        // GET: HomeTasks/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var homeTask = await _context.Tasks
                .Include(h => h.Class)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (homeTask == null)
            {
                return NotFound();
            }

            return View(homeTask);
        }

        // POST: HomeTasks/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var homeTask = await _context.Tasks.FindAsync(id);
            _context.Tasks.Remove(homeTask);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool HomeTaskExists(int id)
        {
            return _context.Tasks.Any(e => e.Id == id);
        }
    }
}

schoool-master/Controllers/SchoolClassesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using MailKit.Net.Smtp;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MimeKit;
using School.Data;
using School.Models;

namespace School.Controllers
{
    public class SchoolClassesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public SchoolClassesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: SchoolClasses
        public async Task<IActionResult> Index()
        {
            _context.Pupils.Load();
            return View(await _context.Classes.ToListAsync());
        }

        // GET: SchoolClasses/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var schoolClass = await _context.Classes
                .FirstOrDefaultAsync(m => m.Id == id);
            if (schoolClass == null)
            {
                return NotFound();
            }

            _context.Pupils.Load();
            _context.Tasks.Load();

            ViewBag.Tasks = from task in _context.Tasks.AsEnumerable()
                            where task.ClassId == id
                                  && task.Deadline >= DateTime.Now
                            group task by task.Deadline;

            return View(schoolClass);
        }

        // GET: SchoolClasses/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: SchoolClasses/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name")] SchoolClass schoolClass)
        {
            if (ModelState.IsValid)
            {
                _context.Add(schoolClass);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(schoolClass);
        }

        // GET: SchoolClasses/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var schoolClass = await _context.Classes.FindAsync(id);
            if (schoolClass == null)
            {
                return NotFound();
            }
            return View(schoolClass);
        }

        // POST: SchoolClasses/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name")] SchoolClass schoolClass)
        {
            if (id != schoolClass.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(schoolClass);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SchoolClassExists(schoolClass.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(schoolClass);
        }

        // GET: SchoolClasses/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var schoolClass = await _context.Classes
                .FirstOrDefaultAsync(m => m.Id == id);
            if (schoolClass == null)
            {
                return NotFound();
            }

            return View(schoolClass);
        }

        // POST: SchoolClasses/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var schoolClass = await _context.Classes.FindAsync(id);
            _context.Classes.Remove(schoolClass);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool SchoolClassExists(int id)
        {
            return _context.Classes.Any(e => e.Id == id);
        }

        [HttpGet]
        public IActionResult SendEmail(int? id)
        {
            _context.Pupils.Load();
            return View("SendEmailForm", _context.Classes.Where(p => p.Id == id).FirstOrDefault());
        }

        [HttpPost]
        public IActionResult SendEmail(int? id, string msg, string subject)
        {
            _context.Pupils.Load();
            MimeMessage message = new MimeMessage();

            MailboxAddress from = new MailboxAddress("Школа д. Зимница", "korsunovs368@gmail.com");
            message.From.Add(from);

            SchoolClass schoolClass = _context.Classes.Where(cl => cl.Id == id).FirstOrDefault();
            foreach(var pupil in schoolClass.Pupils)
            {
                MailboxAddress to = new MailboxAddress(pupil.LastName + " " + pupil.FirstName, pupil.Email);
                
                message.To.Add(to);
                message.Subject = subject;

                BodyBuilder bodyBuilder = new BodyBuilder();
                bodyBuilder.TextBody = msg;

                message.Body = bodyBuilder.ToMessageBody();

                SmtpClient client = new SmtpClient();
                client.Connect("smtp.gmail.com", 465, true);
                client.Authenticate("korsunovs368@gmail.com", "sergoo555");

                client.Send(message);
                client.Disconnect(true);
                client.Dispose();
            }
            return RedirectToAction("Details", "SchoolClasses", new { id });
        }
    }
}

schoool-master/Views/SchoolClasses/Create.cshtml
@model School.Models.SchoolClass

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>SchoolClass</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

schoool-master/Views/SchoolClasses/Delete.cshtml
@model School.Models.SchoolClass

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>SchoolClass</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

schoool-master/Views/SchoolClasses/Details.cshtml
@model School.Models.SchoolClass

@{
    ViewData["Title"] = Model.Name + " класс";
}


<ul class="nav nav-tabs">
    <li class="nav-item">
        <a class="nav-link active" data-toggle="tab" href="#home">Ученики</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" data-toggle="tab" href="#menu1">Задания</a>
    </li>
</ul>

<div class="tab-content">
    <div class="tab-pane container active" id="home">
        <ul class="nav mt-3 mb-3">
            @if (User.Identity.IsAuthenticated)
            {
                <li class="nav-item ml-3">
                    <a asp-action="SendEmail" asp-controller="SchoolClasses" asp-route-id="@Model.Id">
                        Отправить сообщение
                    </a>
                </li>
            }
        </ul>
        <table class="table table-hover text-center">
            <thead>
                <tr>
                    <th>
                        Фамилия
                    </th>
                    <th>
                        Имя
                    </th>
                    <th>
                        Отчество
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var pupil in Model.Pupils)
                {
                    <tr>
                        <td>
                            @pupil.LastName
                        </td>
                        <td>
                            @pupil.FirstName
                        </td>
                        <td>
                            @pupil.MiddleName
                        </td>
                        <td>
                            <a asp-action="Details" asp-controller="SchoolPupils" asp-route-id="@pupil.Id">
                                Перейти
                            </a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>

    <div class="tab-pane container fade" id="menu1">
        <ul class="nav mt-3 mb-3">
            <li class="nav-item">
                @if (User.Identity.IsAuthenticated)
                {
                    <a asp-action="Create" asp-controller="HomeTasks" asp-route-id="@Model.Id">
                        Добавить задание
                    </a>
                }
            </li>
        </ul>
        <table class="table table-hover">
            <thead>
                <tr>
                    <th>
                        Дата
                    </th>
                    <th>
                        Предмет
                    </th>
                    <th>
                        Задание
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach (var taskGroup in ViewBag.Tasks)
                {
                    @foreach (var task in taskGroup)
                    {
                        <tr>
                            <td>
                                @taskGroup.Key.GetDateTimeFormats()[0]
                            </td>
                            <td>
                                @task.Subject
                            </td>
                            <td>
                                @task.Content
                            </td>
                        </tr>
                    }
                }
            </tbody>
        </table>
    </div>
</div>
<a asp-action="Index" asp-controller="SchoolClasses">
    Cписок классов
</a>

schoool-master/Views/SchoolClasses/Edit.cshtml
@model School.Models.SchoolClass

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>SchoolClass</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

schoool-master/Views/SchoolClasses/Index.cshtml
@model IEnumerable<School.Models.SchoolClass>

@{ ViewData["Title"] = "Список классов"; }

<h3>Список классов</h3>
@if (User.Identity.IsAuthenticated)
{
<p>
    <a class="btn btn-primary"
       asp-action="Create"
       asp-controller="SchoolClasses">
        Добавить класс
    </a>
</p>}
<table class="table table-hover text-center">
    <thead>
        <tr>
            <th>
                Класс
            </th>
            <th>
                Учеников
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
        <tr>
            <td>
                @item.Name
            </td>
            <td>
                <span class="badge badge-primary badge-pill">@(item?.Pupils?.Count ?? 0)</span>
            </td>
            <td>
                <a asp-action="Details" asp-controller="SchoolClasses" asp-route-id="@item.Id">
                    Перейти
                </a>
            </td>
            <td>
                <a asp-action="Create" asp-controller="SchoolPupils" >
                    Добавить
                </a>
            </td>
        </tr>}
    </tbody>
</table>

schoool-master/Views/SchoolClasses/SendEmailForm.cshtml
@using School.Models
@model SchoolClass

@{ 
    ViewData["Title"] = "Сообщение классу";
}

<div class="row">
    <div class="col-md-4">
        <h4>Сообщение</h4>
        <hr />
        <form method="post" asp-action="SendEmail" asp-controller="SchoolClasses">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input name="id" type="hidden" value="@Model.Id" />
            <div class="form-group">
                <label for="receiver" class="control-label">
                    Получатель
                </label>
                <input id="receiver" type="text" class="form-control" disabled value="@Model.Name" />
            </div>
            <div class="form-group">
                <label for="subject" class="control-label">
                    Тема сообщения
                </label>
                <input id="subject" name="subject" type="text" required class="form-control" pattern="\S.{3,}"/>
            </div>
            <div class="form-group">
                <label for="msg" class="control-label">
                    Текст сообщения
                </label>
                <textarea id="msg" name="msg" required class="form-control" pattern="\S.{5,}"></textarea>
            </div>
            <div class="form-group">
                <input type="submit" value="Отправить" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Details" asp-controller="SchoolClasses" asp-route-id="@Model.Id">
        Профиль класса
    </a>
</div>