schoool-master/Models/SchoolPupil.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace School.Models
{
    public class SchoolPupil
    {
        public int Id { get; set; }

        [Required]
        [DataType(DataType.Text)]
        [Display(Name = "Имя")]
        public string FirstName { get; set; }

        [Required]
        [DataType(DataType.Text)]
        [Display(Name = "Отчество")]
        public string MiddleName { get; set; }

        [Required]
        [DataType(DataType.Text)]
        [Display(Name = "Фамилия")]
        public string LastName { get; set; }

        [Required]
        [DataType(DataType.EmailAddress)]
        [Display(Name = "Email")]
        public string Email { get; set; }

        [Required]
        [DataType(DataType.Text)]
        [Display(Name = "Адрес")]
        public string Address { get; set; }

        public int ClassId { get; set; }
        public SchoolClass Class { get; set; }

        public List<SchoolMark> Marks { get; set; }
    }
}

schoool-master/Controllers/SchoolMarksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using School.Data;
using School.Models;

namespace School.Controllers
{
    public class SchoolMarksController : Controller
    {
        private readonly ApplicationDbContext _context;

        public SchoolMarksController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: SchoolMarks
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Marks.Include(s => s.Pupil);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: SchoolMarks/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var schoolMark = await _context.Marks
                .Include(s => s.Pupil)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (schoolMark == null)
            {
                return NotFound();
            }

            return View(schoolMark);
        }

        // GET: SchoolMarks/Create
        public IActionResult Create(int id)
        {
            ViewData["PupilId"] = id;
            return View();
        }

        // POST: SchoolMarks/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("LessonDate, Value,Subject,LessonOrderNumber,PupilId")] SchoolMark schoolMark)
        {
            if (ModelState.IsValid)
            {
                _context.Add(schoolMark);
                await _context.SaveChangesAsync();
                return RedirectToAction("Details", "SchoolPupils", new { id = schoolMark.PupilId});
            }
            return View(schoolMark);
        }

        // GET: SchoolMarks/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var schoolMark = await _context.Marks.FindAsync(id);
            if (schoolMark == null)
            {
                return NotFound();
            }
            ViewData["PupilId"] = new SelectList(_context.Pupils, "Id", "Address", schoolMark.PupilId);
            return View(schoolMark);
        }

        // POST: SchoolMarks/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Value,Subject,LessonDate,LessonOrderNumber,PupilId")] SchoolMark schoolMark)
        {
            if (id != schoolMark.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(schoolMark);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SchoolMarkExists(schoolMark.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["PupilId"] = new SelectList(_context.Pupils, "Id", "Address", schoolMark.PupilId);
            return View(schoolMark);
        }

        // GET: SchoolMarks/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var schoolMark = await _context.Marks
                .Include(s => s.Pupil)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (schoolMark == null)
            {
                return NotFound();
            }

            return View(schoolMark);
        }

        // POST: SchoolMarks/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var schoolMark = await _context.Marks.FindAsync(id);
            _context.Marks.Remove(schoolMark);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool SchoolMarkExists(int id)
        {
            return _context.Marks.Any(e => e.Id == id);
        }
    }
}

schoool-master/Controllers/SchoolPupilsController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using School.Data;
using School.Models;
using Syncfusion.HtmlConverter;
using Syncfusion.Pdf;
using MailKit.Net.Smtp;
using MimeKit;
using School.ViewModels;

namespace School.Controllers
{
    public class SchoolPupilsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public SchoolPupilsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: SchoolPupils
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Pupils.Include(s => s.Class);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: SchoolPupils/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var schoolPupil = await _context.Pupils
                .Include(s => s.Class)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (schoolPupil == null)
            {
                return NotFound();
            }

            _context.Classes.Load();
            _context.Marks.Load();
            return View(schoolPupil);
        }

        // GET: SchoolPupils/Create
        public IActionResult Create()
        {
            var model = new CreatePeopleModel();
            model.Classes = new SelectList(_context.Classes,"Id","Name");

            return View(model);
        }

        // POST: SchoolPupils/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CreatePeopleModel model)
        {
            if (ModelState.IsValid)
            {
                //TODO: Mapper
                var schoolPupil = new SchoolPupil();
                schoolPupil.FirstName = model.FirstName;
                schoolPupil.ClassId = model.ClassId;



                //TODO: Business Layer
                _context.Add(schoolPupil);
                await _context.SaveChangesAsync();


                return RedirectToAction(nameof(Index));
            }

            model.Classes = new SelectList(_context.Classes, "Id", "Name");
            return View(model);
        }

        // GET: SchoolPupils/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var schoolPupil = await _context.Pupils.FindAsync(id);
            if (schoolPupil == null)
            {
                return NotFound();
            }
            ViewData["ClassId"] = new SelectList(_context.Classes, "Id", "Id", schoolPupil.ClassId);
            return View(schoolPupil);
        }

        // POST: SchoolPupils/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,FirstName,MiddleName,LastName,Email,Address,ClassId")] SchoolPupil schoolPupil)
        {
            if (id != schoolPupil.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(schoolPupil);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SchoolPupilExists(schoolPupil.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["ClassId"] = new SelectList(_context.Classes, "Id", "Id", schoolPupil.ClassId);
            return View(schoolPupil);
        }

        // GET: SchoolPupils/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var schoolPupil = await _context.Pupils
                .Include(s => s.Class)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (schoolPupil == null)
            {
                return NotFound();
            }

            return View(schoolPupil);
        }

        // POST: SchoolPupils/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var schoolPupil = await _context.Pupils.FindAsync(id);
            _context.Pupils.Remove(schoolPupil);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool SchoolPupilExists(int id)
        {
            return _context.Pupils.Any(e => e.Id == id);
        }

        public IActionResult Report(int? id, DateTime begin, DateTime end)
        {
            _context.Pupils.Load();
            _context.Classes.Load();

            SchoolPupil pupil = _context.Pupils.Where(p => p.Id == id).FirstOrDefault();
            ViewData["FullName"] = pupil.LastName +" "+ pupil.FirstName +" "+ pupil.MiddleName;
            ViewData["Period"] = begin.GetDateTimeFormats()[0] + " по " + end.GetDateTimeFormats()[0];
            ViewData["ClassName"] = pupil.Class.Name; 

            var marksReport = from mark in _context.Marks.AsEnumerable()
                              where mark.Pupil.Id == id && 
                                    mark.LessonDate >= begin &&
                                    mark.LessonDate <= end
                              group mark by mark.Subject into subjectGroup
                              select new AvgMark()
                              {
                                  Subject = subjectGroup.Key,
                                  Value = subjectGroup.Average(g => g.Value)
                              };
            return View(marksReport);
        }

        public IActionResult Pdf(int? id, DateTime begin, DateTime end)
        {
            HtmlToPdfConverter converter = new HtmlToPdfConverter();
            WebKitConverterSettings settings = new WebKitConverterSettings();

            settings.WebKitPath = @"QtBinariesWindows";
            converter.ConverterSettings = settings;

            settings.HttpPostFields.Add("id", id.ToString());
            settings.HttpPostFields.Add("begin", begin.GetDateTimeFormats()[0]);
            settings.HttpPostFields.Add("end", end.GetDateTimeFormats()[0]);

            PdfDocument pdfDocument = converter.Convert("https://localhost:44394/SchoolPupils/Report");

            MemoryStream ms = new MemoryStream();
            pdfDocument.Save(ms);

            ms.Position = 0;

            pdfDocument.Close(true);

            FileStreamResult result = new FileStreamResult(ms, "application/pdf");
            result.FileDownloadName = "Report.pdf";

            return result;
        }

        [HttpGet]
        public IActionResult SendEmail(int? id)
        {
            _context.Pupils.Load();
            return View("SendEmailForm", _context.Pupils.Where(p => p.Id == id).FirstOrDefault());
        }

        [HttpPost]
        public IActionResult SendEmail(int? id, string msg, string subject)
        {
            _context.Pupils.Load();
            SchoolPupil pupil = _context.Pupils.Where(p => p.Id == id).FirstOrDefault();

            MimeMessage message = new MimeMessage();

            MailboxAddress from = new MailboxAddress("Школа д. Зимница",
            "korsunovs368@gmail.com");
            message.From.Add(from);

            MailboxAddress to = new MailboxAddress(pupil.LastName + " " + pupil.FirstName,
            pupil.Email);
            message.To.Add(to);

            message.Subject = subject;

            BodyBuilder bodyBuilder = new BodyBuilder();
            bodyBuilder.TextBody = msg;

            message.Body = bodyBuilder.ToMessageBody();

            SmtpClient client = new SmtpClient();
            client.Connect("smtp.gmail.com", 465, true);
            client.Authenticate("korsunovs368@gmail.com", "sergoo555");

            client.Send(message);
            client.Disconnect(true);
            client.Dispose();

            return RedirectToAction("Details", "SchoolPupils", new{id});
        }
    }
}

schoool-master/Views/SchoolPupils/Create.cshtml
@model School.ViewModels.CreatePeopleModel
@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>SchoolPupil</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            @Html.ValidationSummary()
            <div class="form-group">
                @Html.DisplayNameFor(o=> o.FirstName)
                @Html.TextBoxFor(o=> o.FirstName, new { @class="form-control" } )
                @Html.ValidationMessageFor(o => o.FirstName)
            </div>
          <!--  <div class="form-group">
                <label asp-for="MiddleName" class="control-label"></label>

                <input asp-for="MiddleName" class="form-cosntrol" />
                <span asp-validation-for="MiddleName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address" class="control-label"></label>
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>-->
            <div class="form-group">
                <label asp-for="ClassId" class="control-label"></label>
               <!-- <select asp-for="ClassId" class ="form-control" asp-items="ViewBag.ClassId"></select>-->
                @Html.DropDownListFor(o=> o.ClassId, Model.Classes)
            </div>

            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index" asp-controller="SchoolClasses">
        Cписок классов
    </a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

schoool-master/Views/SchoolPupils/Delete.cshtml
@model School.Models.SchoolPupil

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>SchoolPupil</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MiddleName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MiddleName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Address)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Address)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Class)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Class.Id)
        </dd class>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

schoool-master/Views/SchoolPupils/Details.cshtml
@model School.Models.SchoolPupil

@{
    ViewData["Title"] = "Профиль ученика";
}

<div class="container">
    <h3>@Model.LastName @Model.FirstName @Model.MiddleName</h3>
    <br>
    <ul class="nav nav-tabs" role="tablist">
        <li class="nav-item">
            <a class="nav-link active" data-toggle="tab" href="#home">Данные</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" data-toggle="tab" href="#menu1">Оценки</a>
        </li>
        @if (User.Identity.IsAuthenticated)
        {
            <li class="nav-item">
                <a class="nav-link" data-toggle="tab" href="#menu2">Табель</a>
            </li>
        }
    </ul>

    <div class="tab-content">
        <div id="home" class="container tab-pane active">
            <br>
            <h4>Контактные данные</h4>
            <hr />
            <dl class="row">
                <dt class="col-sm-2">
                    Класс
                </dt>
                <dd class="col-sm-10">
                    @Model.Class.Name
                </dd>
                <dt class="col-sm-2">
                    @Html.DisplayNameFor(model => model.Email)
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.Email)
                </dd>
                <dt class="col-sm-2">
                    @Html.DisplayNameFor(model => model.Address)
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.Address)
                </dd>
            </dl>
            @if (User.Identity.IsAuthenticated)
            {
                <a class="btn btn-primary" asp-action="SendEmail" asp-controller="SchoolPupils" asp-route-id="@Model.Id">
                    Отправить сообщение
                </a>
            }
        </div>
        <div id="menu1" class="container tab-pane fade">
            <ul class="nav mt-3 mb-3">
                @if (User.Identity.IsAuthenticated)
                {
                    <li class="nav-item">
                        <a class="mt-2 mb-2" asp-action="Create" asp-controller="SchoolMarks" asp-route-id="@Model.Id">
                            Добавить отметку
                        </a>
                    </li>
                }
            </ul>
            @if (Model.Marks != null)
            {
                <table class="table table-hover">
                    <thead>
                        <tr>
                            <th>
                                Предмет
                            </th>
                            <th>
                                Дата
                            </th>
                            <th>
                                Оценка
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model.Marks.OrderByDescending(p => p.LessonDate))
                        {
                            <tr>
                                <td>
                                    @item.Subject
                                </td>
                                <td>
                                    @item.LessonDate.GetDateTimeFormats()[0]
                                </td>
                                <td>
                                    @item.Value
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            }
            else
            {
                <div class="alert alert-success">
                    <strong>Информация об оценках отсутствует!</strong>
                </div>
            }
        </div>
        @if (User.Identity.IsAuthenticated)
        {
            <div id="menu2" class="container tab-pane fade">
                <form class="mt-4" asp-action="Pdf" asp-controller="SchoolPupils" asp-route-id="@Model.Id">
                    <div class="form-group">
                        <label class="control-label" for="begin">
                            Начало периода
                        </label>
                        <input id="begin" name="begin" type="date" class="form-control" />
                    </div>
                    <div class="form-group">
                        <label class="control-label" for="end">
                            Конец периода
                        </label>
                        <input id="end" name="end" type="date" class="form-control" />
                    </div>
                    <button class="btn btn-primary">
                        Скачать табель
                    </button>
                </form>
            </div>
        }
        <div class="mt-3">
            <a asp-action="Details" asp-controller="SchoolClasses" asp-route-id="@Model.ClassId">
                Профиль класса
            </a>
        </div>
    </div>
</div>

schoool-master/Views/SchoolPupils/Edit.cshtml
@model School.Models.SchoolPupil

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>SchoolPupil</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MiddleName" class="control-label"></label>
                <input asp-for="MiddleName" class="form-control" />
                <span asp-validation-for="MiddleName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address" class="control-label"></label>
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ClassId" class="control-label"></label>
                <select asp-for="ClassId" class="form-control" asp-items="ViewBag.ClassId"></select>
                <span asp-validation-for="ClassId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

schoool-master/Views/SchoolPupils/Index.cshtml
@model IEnumerable<School.Models.SchoolPupil>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.FirstName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.MiddleName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LastName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Address)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Class)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.FirstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MiddleName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Address)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Class.Id)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

schoool-master/Views/SchoolPupils/Report.cshtml
@using School.Models
@model IEnumerable<AvgMark>

@{ 
    Layout = null;
}

<html>
<head>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
</head>
<body>
    <h5 class="text-center">
        <b>Табель успеваемости</b>
    </h5>
    <h5 class="text-center">
        учащегося @ViewData["ClassName"] класса<br />
        <b>@ViewData["FullName"]</b><br />
        за период с @ViewData["Period"]
        от @DateTime.Now.GetDateTimeFormats()[0]
    </h5>
    <h5 class="text-left">
        Количество предметов: @Model?.Count()
    </h5>
    <table class="table text-center">
        <thead>
            <tr>
                <th>
                    Предмет
                </th>
                <th>
                    Средний балл
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @item.Subject
                    </td>
                    <td>
                        @item.Value
                    </td>
                </tr>
            }
        </tbody>
    </table>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>